language: java
os: linux
jdk: openjdk8

branches:
  only:
    - master

deploy:
  provider: script
  script: 'cp .travis.settings.xml $HOME/.m2/settings.xml && ./publish.sh'
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - amor@dalet.com
      - aprajapati@dalet.com
      - nsmith@dalet.com
      - olockwood@dalet.com
    on_success: change
    on_failure: always
